# Generated by Django 5.0.7 on 2024-07-17 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CityName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=100)),
                ('count_of_search', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UsersLastSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('last_searched', models.DateTimeField(auto_now=True)),
                ('city_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='weather.cityname')),
            ],
        ),
    ]
